data_output:
  root_dir: output
  shared_path: your_sharepath
graph_api:
  client_id: f3d70a72-9356-4818-95c6-7f5224c26296
  client_secret: gAAAAABn0j_vvGhnYkPDzN5iyhJVmRrtdmMSdN0yjPqTjmzDxL0E5voSKwm4QLxfI_ls6x3yEU8Gtvzn0SnwWAPnEFa0z4oqJIGjxZB6CiwxqMDmU4L7qoYkQqL0gTKDRePMhe0OHYj9
  endpoint: https://graph.microsoft.com/v1.0/
  tenant_id: a198d372-128a-4408-b1a7-7786fec4dc85
  authority: 'https://login.microsoftonline.com/{tenant_id}'
  scope:
    - "https://graph.microsoft.com/.default"
