data_output:
  root_dir: output
  shared_path: yourpath

graph_api:
  client_id: yourid
  client_secret: your_encrypted_secret_key_from_fernet.py
  endpoint: https://graph.microsoft.com/v1.0/
  tenant_id: yourtenantid
  
